<?php namespace DschoenbauerTest\SqlControl\Framework;

use Dschoenbauer\SqlControl\Framework\Attribute;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-13 at 17:49:29.
 */
class AttributeTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Attribute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Attribute("test", "value");
    }

    public function testKey()
    {
        $this->assertEquals("NotTest", $this->object->setKey('NotTest')->getKey());
    }
    
    public function testKeyFromConstructor()
    {
        $this->assertEquals("test", $this->object->getKey());
    }

    public function testValue()
    {
        $this->assertEquals("NotValue", $this->object->setValue('NotValue')->getValue());
    }
    
    public function testValueFromConstructor()
    {
        $this->assertEquals("value", $this->object->getValue());
    }

}
