<?php namespace DschoenbauerTest\SqlControl\Framework;

use Dschoenbauer\SqlControl\Framework\Attributes;
use Dschoenbauer\SqlControl\Framework\SqlControlManager;
use Dschoenbauer\SqlControl\Visitor\VisitorInterface;
use PDO;
use PHPUnit_Framework_Assert;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-13 at 17:49:28.
 */
class SqlControlManagerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var SqlControlManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SqlControlManager();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testGetAttributes()
    {
        $this->assertInstanceOf(Attributes::class, $this->object->getAttributes());
    }

    public function testAccept()
    {
        $mock = $this->getMockBuilder(VisitorInterface::class)->getMock();
        $mock->expects($this->once())
            ->method('visitSqlControlManager')
            ->will($this->returnCallback(function($object) {
                    PHPUnit_Framework_Assert::assertEquals($this->object, $object);
                }));
        $this->object->accept($mock);
    }

    public function testAdapter()
    {
        $this->assertInstanceOf(PDO::class, $this->object->setAdapter(new \DschoenbauerTest\SqlControl\Mocks\MockPdo())->getAdapter());
    }

    public function testEventManager(){
        
    }
    
    public function testUpdate()
    {
        $this->object->update();
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
