<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-27 at 17:18:09.
 */
class AbstractAlterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractAlter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $stub = $this->getMockForAbstractClass(AbstractAlter::class);
        $stub->expects($this->any())->method('getQualifyingPattern')->will($this->returnValue(TRUE));
        $stub->expects($this->any())->method('getDataPattern')->will($this->returnValue(TRUE));
        $stub->expects($this->any())->method('getSQL')->will($this->returnValue(TRUE));
        $this->object = $stub;
    }

    public function testCheckCleanRemnant() {
        $actual = "ALTER TABLE Customer";
        $expected = AbstractAlter::SUCCESS_STATENT;
        $this->assertEquals($expected, $this->object->checkRemnant($actual));
    }
    
    public function testCheckCleanRemnantWithWhiteSpace() {
        $actual = "ALTER TABLE Customer
            

";
        $expected = AbstractAlter::SUCCESS_STATENT;
        $this->assertEquals($expected, $this->object->checkRemnant($actual));
    }
    
    public function testCheckDirtyRemnant() {
        $actual = "ALTER TABLE Customer Do Something";
        $this->assertEquals($actual, $this->object->checkRemnant($actual));
    }
    
    public function testCheckFullStatmentWithLineBreak() {
    $sql = "ALTER TABLE Customer   
  ADD COLUMN customer_address1 VARCHAR(45) NULL AFTER customer_enrollDate,
  ADD COLUMN customer_address2 VARCHAR(45) NULL AFTER customer_address1,
  ADD COLUMN customer_city VARCHAR(45) NULL AFTER customer_address2,
  ADD COLUMN state_id int NULL AFTER customer_city,
  ADD COLUMN country_id int NULL AFTER state_id,
  ADD COLUMN customerStatus_id int  NOT NULL AFTER country_id";
    
        $this->assertEquals($sql, $this->object->checkRemnant($sql));
    }
}
