<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:03:04.
 */
class AlterAddIndexTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AlterAddIndex
     */
    protected $object;

    protected function setUp() {
        $this->object = new AlterAddIndex();
    }


    public function testFilterUnique() {
        $sql = "ALTER TABLE Redirect ADD UNIQUE INDEX OneKey (redirect_key); ";
    }

}
