<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

use Ctimt\SqlControl\Framework\SqlChange;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-30 at 17:59:05.
 */
class ConvertReplaceIntoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConvertReplaceInto
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConvertReplaceInto();
        $this->object->setSqlChange(new SqlChange());
    }


    public function testFilter(){
        $sourceData = "REPLACE INTO Product (product_id, product_name, product_maxStorage, product_maxEvents, product_maxActiveEvents, product_maxOrganizers, product_maxDaysBeforeEvent, product_maxDaysAfterEvent, product_maxBandWidth, product_offeringStart, product_offeringStop, product_offeringActive, product_suggestedRetailPrice, distributor_id, product_maxSpeakers, product_priceToDistributor, product_currencyPriceToDistrib, product_billingFrequencyMultiplier, product_billingFrequency, product_emailSubject, product_emailBody, product_public, product_oneTime) VALUES('5017','Invite 6-month unlimited','9999999','9999999','9999999','9999999','9999999','9999999','9999999','2015-09-08 00:00:00','2020-01-01 00:00:00','1','0.00','2','9999999','0.00','0.00','6','m','Invitation to try eventSPRING for free','Dear {user_firstName} {user_lastName},<br><br>\r\nYou organize and participate in meetings all the time and it can get complicated when there are multiple speakers and presentations and even more complicated when there are multiple event organizers!<br><br>\r\neventSPRING is a new, easy solution to organize meetings, seminars and workshops, big and small, with an agenda, speakers, presentations.<br><br>\r\n<a href=\'{route}\'>Click here</a> to spring your events forward with a free 6-month trial: no strings, no credit card.<br><br>\r\neventSPRING is an easy-to-use, online solution to:<ul>\r\n<li>invite speakers and attendees, collect replies and send reminders,</li>\r\n<li>build, share, and keep the event\'s agenda up-to-date,</li>\r\n<li>collect presentations from speakers, share event material with participants and present in the room with or without Internet connection.</li>\r\n</ul>\r\nThank you and let\'s spring forward!','0','0');";
        $result = "DELETE FROM Product where product_id = '5017'";
        $resultTwo = "INSERT INTO Product (product_id, product_name, product_maxStorage, product_maxEvents, product_maxActiveEvents, product_maxOrganizers, product_maxDaysBeforeEvent, product_maxDaysAfterEvent, product_maxBandWidth, product_offeringStart, product_offeringStop, product_offeringActive, product_suggestedRetailPrice, distributor_id, product_maxSpeakers, product_priceToDistributor, product_currencyPriceToDistrib, product_billingFrequencyMultiplier, product_billingFrequency, product_emailSubject, product_emailBody, product_public, product_oneTime) VALUES('5017','Invite 6-month unlimited','9999999','9999999','9999999','9999999','9999999','9999999','9999999','2015-09-08 00:00:00','2020-01-01 00:00:00','1','0.00','2','9999999','0.00','0.00','6','m','Invitation to try eventSPRING for free','Dear {user_firstName} {user_lastName},<br><br>\r\nYou organize and participate in meetings all the time and it can get complicated when there are multiple speakers and presentations and even more complicated when there are multiple event organizers!<br><br>\r\neventSPRING is a new, easy solution to organize meetings, seminars and workshops, big and small, with an agenda, speakers, presentations.<br><br>\r\n<a href=\'{route}\'>Click here</a> to spring your events forward with a free 6-month trial: no strings, no credit card.<br><br>\r\neventSPRING is an easy-to-use, online solution to:<ul>\r\n<li>invite speakers and attendees, collect replies and send reminders,</li>\r\n<li>build, share, and keep the event\'s agenda up-to-date,</li>\r\n<li>collect presentations from speakers, share event material with participants and present in the room with or without Internet connection.</li>\r\n</ul>\r\nThank you and let\'s spring forward!','0','0');";
        $this->assertEquals($result, $this->object->filter($sourceData));
        $this->assertEquals($resultTwo, $this->object->getSqlChange()->getStatement(0));
        
    }
}
