<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:02:51.
 */
class ConvertBooleanTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConvertBoolean
     */
    protected $object;

    protected function setUp() {
        $this->object = new ConvertBoolean;
    }

    public function testFilterBoolean() {
        $original = "ALTER TABLE `ContainerCategory` 
ADD COLUMN `containerCategory_contentExpected` BOOLEAN NULL AFTER `containerCategory_defaultSessionDuration`, 
ADD COLUMN `containerCategory_speakerExpected` BOOLEAN NULL AFTER `containerCategory_contentExpected`;";
        $filtered = "ALTER TABLE `ContainerCategory` 
ADD COLUMN `containerCategory_contentExpected` BIT NULL AFTER `containerCategory_defaultSessionDuration`, 
ADD COLUMN `containerCategory_speakerExpected` BIT NULL AFTER `containerCategory_contentExpected`;";
        $this->assertEquals($filtered, $this->object->filter($original));
    }

}
