<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:03:03.
 */
class ConverTextEscapeCharTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConverTextEscapeChar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConverTextEscapeChar;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ctimt\SqlControl\Adapter\SqlSrv\Filter\ConverTextEscapeChar::filter
     * @todo   Implement testFilter().
     */
    public function testFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
