<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:03:03.
 */
class ConverTextEscapeCharTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConverTextEscapeChar
     */
    protected $object;

    protected function setUp() {
        $this->object = new ConverTextEscapeChar;
    }

    public function testFilter() {
        $this->assertEquals("This is a ''test''",$this->object->filter("This is a \\'test\\'"));
    }

}
