<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-29 at 20:43:04.
 */
class ConvertEnumTest extends \PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new ConvertEnum;
    }

    public function testFilter() {
        $source = "ALTER TABLE Product ADD COLUMN product_billingFrequency ENUM('o','m','y') NULL AFTER product_CurrencyPriceToDistrib";
        $expected = "ALTER TABLE Product ADD COLUMN product_billingFrequency VARCHAR(1) NULL AFTER product_CurrencyPriceToDistrib";
        $this->assertEquals($expected, $this->object->filter($source));
    }
    
    public function testFilterWithVaryingLengths() {
        $source = "ALTER TABLE Product ADD COLUMN product_billingFrequency ENUM('one','many','yahoo') NULL AFTER product_CurrencyPriceToDistrib";
        $expected = "ALTER TABLE Product ADD COLUMN product_billingFrequency VARCHAR(5) NULL AFTER product_CurrencyPriceToDistrib";
        $this->assertEquals($expected, $this->object->filter($source));
    }

}
