<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-30 at 15:42:47.
 */
class ConvertDoubleQuoteTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConvertDoubleQuote
     */
    protected $object;

    protected function setUp() {
        $this->object = new ConvertDoubleQuote();
    }

    public function testFilterConvertQuotes() {
        $test = "This has \"double\" quotes";
        $expected = "This has 'double' quotes";
        $this->assertEquals($expected, $this->object->filter($test));
    }
    
    public function testFilterExistingSingleQuotes() {
        $test = "This has 'single' quotes";
        $this->assertEquals($test, $this->object->filter($test));
    }
    
    public function testFilterDoubleWithSingleInside() {
        $test = "This is example html \"<a href='test.html' color='black'>Test</a>\"";
        $result = "This is example html '<a href=''test.html'' color=''black''>Test</a>'";
        $this->assertEquals($result, $this->object->filter($test));
    }

}
