<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:02:50.
 */
class InsertIdentityTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var InsertIdentity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new InsertIdentity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ctimt\SqlControl\Adapter\SqlSrv\Filter\InsertIdentity::filter
     * @todo   Implement testFilter().
     */
    public function testFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ctimt\SqlControl\Adapter\SqlSrv\Filter\InsertIdentity::getSqlChange
     * @todo   Implement testGetSqlChange().
     */
    public function testGetSqlChange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ctimt\SqlControl\Adapter\SqlSrv\Filter\InsertIdentity::setSqlChange
     * @todo   Implement testSetSqlChange().
     */
    public function testSetSqlChange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
