<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

use Ctimt\SqlControl\Framework\SqlChange;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:03:02.
 */
class ManageCreateKeysTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ManageCreateKeys
     */
    protected $object;

    protected function setUp() {
        $this->object = new ManageCreateKeys();
        $this->object->setSqlChange(new SqlChange());
    }

    public function testFilter() {
        $result = "CREATE TABLE User (
        user_id int(10) unsigned NOT NULL AUTO_INCREMENT
        PRIMARY KEY (user_id),
        
       
        )";
        $this->assertEquals($result, $this->object->filter($this->getStatement()));
    }

    public function getStatement() {
        return "CREATE TABLE User (
        user_id int(10) unsigned NOT NULL AUTO_INCREMENT
        PRIMARY KEY (user_id),
        UNIQUE KEY UniqueEmail (user_email),
        KEY fk_TblProfile_profileStatus_1_idx (userStatus_id)
        )";
    }

}
