<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 20:06:52.
 */
class ManageVarcharMaxTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ManageVarcharMax
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ManageVarcharMax();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testFilterOverLimit() {
        $this->assertEquals($this->getSql('max'), $this->object->filter($this->getSql('10000')));
    }
    public function testFilterUnderLimit() {
        $this->assertEquals($this->getSql('1000'), $this->object->filter($this->getSql('1000')));
    }

    private function getSql($size){
        return "CREATE TABLE NotificationQueue( 
    notificationQueue_id int NOT NULL IDENTITY, 
    notificationQueue_message VARCHAR($size), 
    PRIMARY KEY (notificationQueue_id) 
)";
    }
}
