<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:02:56.
 */
class RemoveFieldByFieldCharTypeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RemoveFieldByFieldCharType
     */
    protected $object;

    protected function setUp() {
        $this->object = new RemoveFieldByFieldCharType();
    }

    public function testFilter() {

    }

}
