<?php

namespace Ctimt\SqlControl\Adapter\SqlSrv\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 18:02:53.
 */
class ReplaceAutoIncrementTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ReplaceAutoIncrement
     */
    protected $object;

    protected function setUp() {
        $this->object = new ReplaceAutoIncrement();
    }

    public function testFilter() {
        $statement = "CREATE TABLE `Task2Role` (
  `task2Role_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
        `Task2Role_permission` int(11) NOT NULL DEFAULT '0',
        `role_id` int(10) unsigned NOT NULL,
        `task_id` int(11) NOT NULL";

        $result = "CREATE TABLE `Task2Role` (
  `task2Role_id` int(10) unsigned IDENTITY,
        `Task2Role_permission` int(11) NOT NULL DEFAULT '0',
        `role_id` int(10) unsigned NOT NULL,
        `task_id` int(11) NOT NULL";
        $this->assertEquals($result, $this->object->filter($statement));
    }

}
