<?php namespace Ctimt\SqlControl\Status;

use Ctimt\SqlControl\Status\Fail;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:08:20.
 */
class FailTest extends \CtimtTest\SqlControl\Mocks\TestStatus
{

    /**
     * @var Fail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->configure(new Fail(), 'Fail', false, false);
    }
}
