<?php namespace Ctimt\SqlControl\Parser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 17:40:33.
 */
class FileVersionTest  extends \CtimtTest\SqlControl\Parser\TestParser
{

    /**
     * @var FileVersion
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileVersion();
    }

    public function testParse()
    {
        $this->assertEquals('1.1.9',$this->object->parse($this->addName($this->getBaseMock(),'Test.1.1.9.sql')));
        $this->assertEquals('1.1.0',$this->object->parse($this->addName($this->getBaseMock(),'Test.1.1.sql')));
        $this->assertEquals('1.0.0',$this->object->parse($this->addName($this->getBaseMock(),'Test.1.sql')));
        $this->assertEquals('0.0.0',$this->object->parse($this->addName($this->getBaseMock(),'Test.sql')));
    }
}
