<?php namespace Dschoenbauer\SqlControl\Parser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 17:40:33.
 */
class FileSqlStatementsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FileSqlStatements
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileSqlStatements;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Dschoenbauer\SqlControl\Parser\FileSqlStatements::Parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
