<?php namespace Ctimt\SqlControl\Parser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 17:40:33.
 */
class FileSqlStatementsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FileSqlStatements
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new FileSqlStatements();
    }

    public function testParse()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
