<?php namespace Ctimt\SqlControl\Framework;

use Ctimt\SqlControl\Framework\Attribute;
use Ctimt\SqlControl\Framework\Attributes;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-13 at 17:49:29.
 */
class AttributesTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Attributes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Attributes();
    }

    public function testAdd()
    {
        $this->assertEquals('value',$this->object->add('test', 'value')->getValue('test'));
    }
    
    public function testGetValueNonExistantKey(){
        $this->assertEquals('Not There',$this->object->getValue('test','Not There'));
    }

    public function testGetAttribute()
    {
        $this->object->add('test', 'value');
        $attrib = $this->object->getAttribute('test');
        $this->assertInstanceOf(Attribute::class, $attrib);
    }
}
