<?php namespace CtimtTest\SqlControl\Status;

use Ctimt\SqlControl\Status\Loaded;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:08:20.
 */
class LoadedTest extends \CtimtTest\SqlControl\Status\TestStatus
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->configure(new Loaded(), 'Loaded', true, false);
    }
}
