<?php namespace DschoenbauerTest\SqlControl\Status;

use Dschoenbauer\SqlControl\Status\PendingLoad;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:08:21.
 */
class PendingLoadTest extends \DschoenbauerTest\SqlControl\Status\TestStatus
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->configure(new PendingLoad(),'Pending Load',false,true);
    }

}
