<?php namespace DschoenbauerTest\SqlControl\Status;

use Dschoenbauer\SqlControl\Status\Skipped;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:08:21.
 */
class SkippedTest extends \DschoenbauerTest\SqlControl\Status\TestStatus
{

    /**
     * @var Skipped
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->configure(new Skipped(),'Skipped',false,false);
    }

}
