<?php namespace DschoenbauerTest\SqlControl\Status;

use Dschoenbauer\SqlControl\Status\Success;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:08:20.
 */
class SuccessTest extends \DschoenbauerTest\SqlControl\Status\TestStatus
{

    protected function setUp()
    {
        $this->configure(new Success(), 'Success', true, false);
    }
}
